apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-http-server
  namespace: keda-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-http-server
  template:
    metadata:
      labels:
        app: go-http-server
    spec:
      containers:
      - image: quay.io/dyapas325/go-http-server:latest
        name: go-http-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "25m"
          limits:
            cpu: "50m"
