apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-http-server-prom
  name: go-http-server-prom
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-http-server-prom
